### ISSUE TITLE
v1.3.1 not available on rubygems.org

### ISSUE THREAD

**Issue by alexactmd** [ruby-hl7/ruby-hl7#104]
Looks like v1.3.1 was released a month or so ago, but I don't see it at https://rubygems.org/gems/ruby-hl7/. Can someone please upload it?

**Comment by Stratus3D** [comment]
I'm not sure who has permission to do this. I may have permission but don't have time to look into this right now. @mogox can you do this?

**Comment by mogox** [comment]
Oops, yeah, I can take care of this later today.

**Comment by mogox** [comment]
Done! https://rubygems.org/gems/ruby-hl7/versions/1.3.1
