### ISSUE TITLE
Gem on RubyGems.org doesn't contain latest code

### ISSUE THREAD

**Issue by calebwoods** [ruby-hl7/ruby-hl7#11]
I was attempting use the gem as installed from [RubyGems.org](http://rubygems.org/gems/ruby-hl7), but it appears that not all the changes that have been made to the project have been release to RubyGems.

For example here are the first few lines from RubyGems.org version of the orc.rb segment file.

```ruby
# encoding: UTF-8
require 'ruby-hl7'
class HL7::Message::Segment::ORC < HL7::Message::Segment
  add_field :order_control
  add_field :placer_order_number
  add_field :filler_order_number
  add_field :placer_group_number
```

Looking at the project there are changes made 2 years ago that weren't release to RubyGems.org, such as adding children to the orc.rb file.

```ruby
# encoding: UTF-8
require 'ruby-hl7'
class HL7::Message::Segment::ORC < HL7::Message::Segment
  weight 88 # obr.weight-1
  has_children [:OBR]
  add_field :order_control
  add_field :placer_order_number
  add_field :filler_order_number
  add_field :placer_group_number
```

Any chance a new version could get released to RubyGems.org or do I need to rely on the Github version of the gem?

Also looks the version number hasn't been incremented in over 2 years although there have been active changes.  Because I am using this gem with bundler it would be great to see the version incremented to handle updates properly.

Thanks!  I appreciate all the works that's gone into this project.

**Comment by Stratus3D** [comment]
@mogox You did publish another release to rubygems right? Can this issue be closed?

**Comment by mogox** [comment]
oh yes! thanks @Stratus3D
