### ISSUE TITLE
PV2 is missing PV2.40 "Admission Level of Care Code"

### ISSUE THREAD

**Issue by jhumphrey1** [ruby-hl7/ruby-hl7#113]
Here's an example: https://hl7-definition.caristix.com/v2/HL7v2.5.1/Segments/PV2

Causes any use of index to be off by one at anything above 40

**Comment by LucasMontorio** [comment]
This issue was fixed at last in the following PR: https://github.com/ruby-hl7/ruby-hl7/pull/138
