### ISSUE TITLE
Need for maintainers?

### ISSUE THREAD

**Issue by LucasMontorio** [ruby-hl7/ruby-hl7#127]
Hi everyone, 

It seems that the gem hasn't been maintained for quite some time and might deserve a bit of attention. I would be happy to contribute but seeing PRs open since 2019 makes me think it might not be very productive.
Is there anyone available to review in case of new contributions? Or would you be considering adding new maintainers?

Thanks a lot!

**Comment by Stratus3D** [comment]
Hi @LucasMontorio , yes, this project is in need of maintainers. You are welcome to contribute, but I don't have a lot of time to review PRs these days.

I would consider adding an existing contributor as a maintainer but only if they have contributed multiple PRs (merged or unmerged). If you have any suggestions on who I should add let me know. Thanks!
