### ISSUE TITLE
HL7::Message::Segment uses obsolete syntax

### ISSUE THREAD

**Issue by kodger4** [ruby-hl7/ruby-hl7#36]
The Segment class defines it's attributes using the "attr" method - and adds an optional boolean argument to the :segment_parent attribute (which would previous have made it both readable and writeable)

From the source of the [Module's attr() function](http://www.ruby-doc.org/core-1.9.2/Module.html#method-i-attr), it appears that since Ruby 1.9.x, that syntax for making an attribute readable and writable is obsolete.

Looks like it will still have the same affect - it will still allow the syntax, and produce a writeable attribute - but it will also print out a warning message. Since Ruby 1.8.6 and up (as required by the gem) all support attr_accessor and attr_reader, should we be using those instead?

**Comment by LucasMontorio** [comment]
This was solved in https://github.com/ruby-hl7/ruby-hl7/commit/aa5108d83f74fde86e53ce22eb4ff93acedfd134
