### ISSUE TITLE
Can't set ParserConfig

### ISSUE THREAD

**Issue by micred** [ruby-hl7/ruby-hl7#47]
I can't find a method for setting ParserConfig ( :empty_segment_is_error => false ).
How to set and prevent the raise of the exception?

**Comment by mogox** [comment]
Hey @micred, would you mind providing an example of the error you want to avoid?

I usually do
```ruby
# where data is 
File.open(filename, 'r') do |file|
  data = file.read
end

message = HL7::Message.parse(data)
```

And if there are empty segments it would just ignore it.  Let me know if you need something else

**Comment by micred** [comment]
Hi @mogox, I was simply not finding the option to permit empty segments, but I found it looking into the code:
```
HL7.ParserConfig[:empty_segment_is_error] = false
```

I suggest adding it to the documentation.

**Comment by mogox** [comment]
Hey, yeah I think you're right and we should have a better documentation, reading the PRs and the code it's helpful but this should be easier.

I'll think about something else! Thank you @micred
