### ISSUE TITLE
ZPS and other custom segments

### ISSUE THREAD

**Issue by mogox** [ruby-hl7/ruby-hl7#49]
Hello @ruby-hl7/maintainers, 

In conversations with my co-workers we're thinking about the advantages/disadvantages of adding a ZPS  or another custom segments to the gem.

- If we add the ZPS segment and other custom segments we could avoid having each developer add them and we could consolidate the development and fixes of the segments.

- If we don't add the segments one other option (suggested by @adamstegman and @mitch-lindsay) would be to have the segments in a separate gem (let's say ```ruby-hl7-zps```, ```ruby-hl7-zpe``` and so on) so we could add those segments on demand.

I'm leaning more in favor of the second option but I'd want to open up the discussion.

Thank you all!

**Comment by adamstegman** [comment]
> If we add the ZPS segment and other custom segments we could avoid having each developer add them and we could consolidate the development and fixes of the segments.

This would be great as long as we don't have conflicting implementations for different vendors.

**Comment by adamstegman** [comment]
@mogox we should probably close this based on ruby-hl7/ruby-hl7-zef and ruby-hl7/ruby-hl7-zps :)

**Comment by mogox** [comment]
Done! thanks @adamstegman
