### ISSUE TITLE
HL7::EmptySegmentNotAllowed Error

### ISSUE THREAD

**Issue by bradbajuz** [ruby-hl7/ruby-hl7#65]
In my Rails app, I'm trying to parse HL7 messages by pulling them from the database (saved as text):

```
raw_input = @pf_order.hl7_document
msg = HL7::Message.new(raw_input)
msg[:OBR].universal_service_id
```

But I keep on getting `HL7::EmptySegmentNotAllowed`

I've verified that message isn't empty, so what is the correct way to parse this data?

**Comment by vais** [comment]
This may have something to do with line breaks in `raw_input` - i.e. `\n` vs `\r\n` vs `\r`. I got bitten by this a while back, and if I recall correctly, it wants `\r` line breaks. Sorry I don't have the code handy right now, but try to change line breaks in your `raw_input` and see if that helps.

**Comment by bradbajuz** [comment]
Great. Thanks for your help.
