### ISSUE TITLE
HL7::Message::Segment::Default warning and error 

### ISSUE THREAD

**Issue by jptingle-strivelabs** [ruby-hl7/ruby-hl7#70]
A warning and then fatal error just started showing up in my CI (Codeship.com) test build with a bundle install.  Been using the gem for 2 yrs with no problems.

The warning is as follows:
segment_default.rb:9: warning: toplevel constant Segment referenced by HL7::Message::Segment

Then the bundle install fails with a: 
rake aborted!
Bundler::GemRequireError: There was an error while trying to load the gem 'ruby-hl7'.
Gem Load Error is: superclass must be a Class (Module given)
Backtrace for gem load error is:
/home/rof/cache/bundler/ruby/2.3.0/bundler/gems/ruby-hl7-1fab0c25fb20/lib/segment_default.rb:9:in `<top (required)>'

My app uses ruby '2.3.1' and 'rails', '4.2.7.1'

Has anybody run into this?

**Comment by jptingle-strivelabs** [comment]
Not sure if related to changes in Rails autoloading as version got closer to 5 or upgrades in Ruby or the combo but I ended up moving the hl7 module files (all except ruby-hl7.rb) to an hl7 subdirectory under lib.  Local specs run fine and the gem places nicely in our rails app.

hl7/message.rb
etc.

I'm in a "don't care why, just need to get it back out to production" mode.  If anybody else runs into this, let me know.

**Comment by mogox** [comment]
Hey @jptingle-strivelabs thank you for logging this issue.  Do you happen to have test application/env where we can test this?

Have you tried the latest version with Rails 5?

cc @mitch-lindsay  @ruby-hl7/contributors

**Comment by mitch-lindsay** [comment]
We haven't seen any problems with ruby-hl7 related modules while running Rails 5 but I will keep my eye out for anything.
