### ISSUE TITLE
Is FT1 segment supported?

### ISSUE THREAD

**Issue by raulperezalejo** [ruby-hl7/ruby-hl7#76]
Hello, the FT1 segment is not inside the segment folder, so i may guess is not supported by this project. 
Is there any plan to supported?
does anyone know some gem that support it? 
recommendations? 
thanks

**Comment by mitch-lindsay** [comment]
It's not currently implemented but I see no reason not to.  If you want to define it and put up PR that would be great.  Otherwise I will likely implement it in the near future.
