### ISSUE TITLE
Is it time to release v1.2.1?

### ISSUE THREAD

**Issue by vais** [ruby-hl7/ruby-hl7#78]
@mogox https://github.com/ruby-hl7/ruby-hl7/compare/ruby-hl7:v1.2.0...master
Mostly just want to get rid of those pesky `Fixnum` warnings on Ruby 2.4 :wink:

**Comment by mitch-lindsay** [comment]
I drafted a release https://github.com/ruby-hl7/ruby-hl7/releases/tag/v1.2.1 but I'd like @mogox to review.

**Comment by mogox** [comment]
Thanks for drafting the release! I'll try to get out the release 1.2.1 tonight

**Comment by mogox** [comment]
Done https://rubygems.org/gems/ruby-hl7/
